apiVersion: apps/v1
kind: Deployment
metadata:
  name: testappfrontend-deployment
  namespace: testapp
spec:
  replicas: 1
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: testapp
  template:
    metadata:
      labels:
        app: testapp
    spec:
      containers:
        - name: testappfrontend
          image: ernom/testapp:v1.0.2
          ports:
            - containerPort: 80
