apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
    name: frontend-ingress
    namespace: testapp
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`testapp.74.220.27.234.nip.io`)
      kind: Rule
      services:
        - name: testappfronted-svc
          port: 80
