apiVersion: v1
kind: Service
metadata:
  name: testappfronted-svc
  namespace: testapp
  labels:
    app: testapp
spec:
  selector:
    app: testapp
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP

